/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthSigninIndexRouteImport } from './routes/_auth/signin/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/_auth/verify-email/index'
import { Route as MainBookmarksIndexRouteImport } from './routes/_main/bookmarks/index'
import { Route as MainChatIndexRouteImport } from './routes/_main/chat/index'
import { Route as MainCreateIndexRouteImport } from './routes/_main/create/index'
import { Route as MainFeedIndexRouteImport } from './routes/_main/feed/index'
import { Route as MainNotificationsIndexRouteImport } from './routes/_main/notifications/index'
import { Route as MainProfileIndexRouteImport } from './routes/_main/profile/index'
import { Route as MainSearchIndexRouteImport } from './routes/_main/search/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainSettingsCloseFriendsRouteImport } from './routes/_main/settings/close-friends'
import { Route as MainPostsPostIdIndexRouteImport } from './routes/_main/posts/$postId/index'
import { Route as MainProfileEditIndexRouteImport } from './routes/_main/profile/edit/index'
import { Route as MainUsersUsernameIndexRouteImport } from './routes/_main/users/$username/index'
import { Route as MainUsersUsernameFollowersFollowingRouteImport } from './routes/_main/users/$username/followers-following'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainBookmarksIndexRoute = MainBookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainChatIndexRoute = MainChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCreateIndexRoute = MainCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFeedIndexRoute = MainFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNotificationsIndexRoute = MainNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSearchIndexRoute = MainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsCloseFriendsRoute =
  MainSettingsCloseFriendsRouteImport.update({
    id: '/settings/close-friends',
    path: '/settings/close-friends',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainPostsPostIdIndexRoute = MainPostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileEditIndexRoute = MainProfileEditIndexRouteImport.update({
  id: '/profile/edit/',
  path: '/profile/edit/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersUsernameIndexRoute = MainUsersUsernameIndexRouteImport.update({
  id: '/users/$username/',
  path: '/users/$username/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersUsernameFollowersFollowingRoute =
  MainUsersUsernameFollowersFollowingRouteImport.update({
    id: '/users/$username/followers-following',
    path: '/users/$username/followers-following',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/close-friends': typeof MainSettingsCloseFriendsRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/signin/': typeof AuthSigninIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/bookmarks/': typeof MainBookmarksIndexRoute
  '/chat/': typeof MainChatIndexRoute
  '/create/': typeof MainCreateIndexRoute
  '/feed/': typeof MainFeedIndexRoute
  '/notifications/': typeof MainNotificationsIndexRoute
  '/profile/': typeof MainProfileIndexRoute
  '/search/': typeof MainSearchIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/users/$username/followers-following': typeof MainUsersUsernameFollowersFollowingRoute
  '/posts/$postId/': typeof MainPostsPostIdIndexRoute
  '/profile/edit/': typeof MainProfileEditIndexRoute
  '/users/$username/': typeof MainUsersUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/close-friends': typeof MainSettingsCloseFriendsRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/signin': typeof AuthSigninIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/verify-email': typeof AuthVerifyEmailIndexRoute
  '/bookmarks': typeof MainBookmarksIndexRoute
  '/chat': typeof MainChatIndexRoute
  '/create': typeof MainCreateIndexRoute
  '/feed': typeof MainFeedIndexRoute
  '/notifications': typeof MainNotificationsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/search': typeof MainSearchIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/users/$username/followers-following': typeof MainUsersUsernameFollowersFollowingRoute
  '/posts/$postId': typeof MainPostsPostIdIndexRoute
  '/profile/edit': typeof MainProfileEditIndexRoute
  '/users/$username': typeof MainUsersUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/settings/close-friends': typeof MainSettingsCloseFriendsRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/signin/': typeof AuthSigninIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/_main/bookmarks/': typeof MainBookmarksIndexRoute
  '/_main/chat/': typeof MainChatIndexRoute
  '/_main/create/': typeof MainCreateIndexRoute
  '/_main/feed/': typeof MainFeedIndexRoute
  '/_main/notifications/': typeof MainNotificationsIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/search/': typeof MainSearchIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/users/$username/followers-following': typeof MainUsersUsernameFollowersFollowingRoute
  '/_main/posts/$postId/': typeof MainPostsPostIdIndexRoute
  '/_main/profile/edit/': typeof MainProfileEditIndexRoute
  '/_main/users/$username/': typeof MainUsersUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/close-friends'
    | '/forgot-password/'
    | '/reset-password/'
    | '/signin/'
    | '/signup/'
    | '/verify-email/'
    | '/bookmarks/'
    | '/chat/'
    | '/create/'
    | '/feed/'
    | '/notifications/'
    | '/profile/'
    | '/search/'
    | '/settings/'
    | '/users/$username/followers-following'
    | '/posts/$postId/'
    | '/profile/edit/'
    | '/users/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/close-friends'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/bookmarks'
    | '/chat'
    | '/create'
    | '/feed'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/users/$username/followers-following'
    | '/posts/$postId'
    | '/profile/edit'
    | '/users/$username'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/_main/settings/close-friends'
    | '/_auth/forgot-password/'
    | '/_auth/reset-password/'
    | '/_auth/signin/'
    | '/_auth/signup/'
    | '/_auth/verify-email/'
    | '/_main/bookmarks/'
    | '/_main/chat/'
    | '/_main/create/'
    | '/_main/feed/'
    | '/_main/notifications/'
    | '/_main/profile/'
    | '/_main/search/'
    | '/_main/settings/'
    | '/_main/users/$username/followers-following'
    | '/_main/posts/$postId/'
    | '/_main/profile/edit/'
    | '/_main/users/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin/': {
      id: '/_auth/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-email/': {
      id: '/_auth/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/bookmarks/': {
      id: '/_main/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof MainBookmarksIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/chat/': {
      id: '/_main/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof MainChatIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/create/': {
      id: '/_main/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof MainCreateIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/feed/': {
      id: '/_main/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof MainFeedIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/notifications/': {
      id: '/_main/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof MainNotificationsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/search/': {
      id: '/_main/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof MainSearchIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/close-friends': {
      id: '/_main/settings/close-friends'
      path: '/settings/close-friends'
      fullPath: '/settings/close-friends'
      preLoaderRoute: typeof MainSettingsCloseFriendsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/posts/$postId/': {
      id: '/_main/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof MainPostsPostIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/edit/': {
      id: '/_main/profile/edit/'
      path: '/profile/edit'
      fullPath: '/profile/edit/'
      preLoaderRoute: typeof MainProfileEditIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users/$username/': {
      id: '/_main/users/$username/'
      path: '/users/$username'
      fullPath: '/users/$username/'
      preLoaderRoute: typeof MainUsersUsernameIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users/$username/followers-following': {
      id: '/_main/users/$username/followers-following'
      path: '/users/$username/followers-following'
      fullPath: '/users/$username/followers-following'
      preLoaderRoute: typeof MainUsersUsernameFollowersFollowingRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainSettingsCloseFriendsRoute: typeof MainSettingsCloseFriendsRoute
  MainBookmarksIndexRoute: typeof MainBookmarksIndexRoute
  MainChatIndexRoute: typeof MainChatIndexRoute
  MainCreateIndexRoute: typeof MainCreateIndexRoute
  MainFeedIndexRoute: typeof MainFeedIndexRoute
  MainNotificationsIndexRoute: typeof MainNotificationsIndexRoute
  MainProfileIndexRoute: typeof MainProfileIndexRoute
  MainSearchIndexRoute: typeof MainSearchIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainUsersUsernameFollowersFollowingRoute: typeof MainUsersUsernameFollowersFollowingRoute
  MainPostsPostIdIndexRoute: typeof MainPostsPostIdIndexRoute
  MainProfileEditIndexRoute: typeof MainProfileEditIndexRoute
  MainUsersUsernameIndexRoute: typeof MainUsersUsernameIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainSettingsCloseFriendsRoute: MainSettingsCloseFriendsRoute,
  MainBookmarksIndexRoute: MainBookmarksIndexRoute,
  MainChatIndexRoute: MainChatIndexRoute,
  MainCreateIndexRoute: MainCreateIndexRoute,
  MainFeedIndexRoute: MainFeedIndexRoute,
  MainNotificationsIndexRoute: MainNotificationsIndexRoute,
  MainProfileIndexRoute: MainProfileIndexRoute,
  MainSearchIndexRoute: MainSearchIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainUsersUsernameFollowersFollowingRoute:
    MainUsersUsernameFollowersFollowingRoute,
  MainPostsPostIdIndexRoute: MainPostsPostIdIndexRoute,
  MainProfileEditIndexRoute: MainProfileEditIndexRoute,
  MainUsersUsernameIndexRoute: MainUsersUsernameIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
